wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
bs:
  desc: null
  value: 629
data_path:
  desc: null
  value: datas/Prescriptions/
dim:
  desc: null
  value: 82
epochs:
  desc: null
  value: 35
lr:
  desc: null
  value: 0.08271602660639067
margin:
  desc: null
  value: 2
model:
  desc: null
  value: TransE
ns:
  desc: null
  value: 46
p:
  desc: null
  value: 2
