wandb_version: 1

bs:
  value: 381
data_path:
  value: datas/Prescriptions/
dim:
  value: 170
epochs:
  value: 25
lr:
  value: 0.05289120025333388
margin:
  value: 8
model:
  value: DistMult
ns:
  value: 8
p:
  value: 2
