wandb_version: 1

bs:
  value: 629
data_path:
  value: datas/Prescriptions/
dim:
  value: 82
epochs:
  value: 35
lr:
  value: 0.08271602660639067
margin:
  value: 2
model:
  value: TransE
ns:
  value: 46
p:
  value: 2
