wandb_version: 1

bs:
  value: 677
data_path:
  value: datas/Prescriptions/
dim:
  value: 97
epochs:
  value: 39
lr:
  value: 0.06709764542273244
margin:
  value: 3
model:
  value: TransE
ns:
  value: 19
p:
  value: 1
